server_addr: ":8080"
db_user: "testCash"
db_password: "testCash"
db_host: "localhost"
db_port: "5432"
db_name: "CashDB"
redis_addr: "localhost:6379"
jwt_secret: "your_secret_key"
admin_token: "test12345test"
